0x70 const> TTY-CELL-FG
0x7 const> TTY-CELL-BG

0x3 const> TTY-CELL-BRIGHTNESS
0xFC const> TTY-CELL-ATTRS

0x0 const> TTY-CELL-NORMAL
0x1 const> TTY-CELL-DIM
0x2 const> TTY-CELL-BRIGHT
0x2 const> TTY-CELL-ATTR-BOLD
0x3 const> TTY-CELL-OFF
0x3 const> TTY-CELL-ATTR-INVIS
0x4 const> TTY-CELL-INVERT
0x08 const> TTY-CELL-ATTR-BOX
0x10 const> TTY-CELL-ATTR-ITALIC
0x20 const> TTY-CELL-ATTR-UNDERLINE
0x40 const> TTY-CELL-ATTR-STRIKE
0x80 const> TTY-CELL-ATTR-BLINK
